"""
usability_oracle.core — Fundamental types, enumerations, protocols, errors,
configuration, and physical/cognitive constants.

Re-exports every public symbol so that downstream code can write::

    from usability_oracle.core import Point2D, AccessibilityRole, OracleConfig
"""

from __future__ import annotations

# --- types ------------------------------------------------------------------
from usability_oracle.core.types import (
    Point2D,
    BoundingBox,
    Interval,
    AccessibilityNodeId,
    TaskId,
    StateId,
    ActionId,
    CostTuple,
    TrajectoryStep,
    Trajectory,
    PolicyDistribution,
)

# --- enums ------------------------------------------------------------------
from usability_oracle.core.enums import (
    AccessibilityRole,
    BottleneckType,
    CognitiveLaw,
    EditOperationType,
    RegressionVerdict,
    PipelineStage,
    ComparisonMode,
    OutputFormat,
    AlignmentPass,
    Severity,
    MotorChannel,
    PerceptualChannel,
)

# --- protocols --------------------------------------------------------------
from usability_oracle.core.protocols import (
    Parser,
    Aligner,
    CostModel,
    PolicyComputer,
    BottleneckClassifier,
    RepairSynthesizer,
    OutputFormatter,
    PipelineStageExecutor,
    Validator,
    Serializable,
    CacheProvider,
    WCAGEvaluator,
    GomsPredictor,
    ChannelAnalyzer,
)

# --- errors -----------------------------------------------------------------
from usability_oracle.core.errors import (
    UsabilityOracleError,
    ParseError,
    InvalidAccessibilityTreeError,
    MalformedHTMLError,
    AlignmentError,
    IncompatibleTreesError,
    CostModelError,
    InvalidParameterError,
    ConvergenceError,
    MDPError,
    StateSpaceExplosionError,
    UnreachableStateError,
    PolicyError,
    NumericalInstabilityError,
    BisimulationError,
    PartitionError,
    BottleneckError,
    ClassificationError,
    ComparisonError,
    InsufficientDataError,
    RepairError,
    SynthesisTimeoutError,
    InfeasibleRepairError,
    ConfigError,
    ValidationError,
    PipelineError,
    StageError,
    CacheError,
)

# --- config -----------------------------------------------------------------
from usability_oracle.core.config import (
    OracleConfig,
    ParserConfig,
    AlignmentConfig,
    CognitiveConfig,
    MDPConfig,
    PolicyConfig,
    BisimulationConfig,
    ComparisonConfig,
    RepairConfig,
    PipelineConfig,
    OutputConfig,
)

# --- constants --------------------------------------------------------------
from usability_oracle.core.constants import (
    FITTS_A_RANGE,
    FITTS_B_RANGE,
    HICK_A_RANGE,
    HICK_B_RANGE,
    WORKING_MEMORY_CAPACITY,
    WORKING_MEMORY_DECAY_HALF_LIFE,
    VISUAL_SEARCH_EFFICIENT_SLOPE,
    VISUAL_SEARCH_INEFFICIENT_SLOPE,
    MOTOR_PREPARATION_TIME,
    MOTOR_EXECUTION_TIME,
    PERCEPTION_TIME_VISUAL,
    PERCEPTION_TIME_AUDITORY,
    SACCADE_DURATION,
    FIXATION_DURATION,
    PIXEL_TO_MM,
    DISPLAY_PPI,
    CHANNEL_CAPACITIES,
    MINIMUM_TARGET_SIZE_PX,
    RECOMMENDED_TARGET_SIZE_PX,
    MAX_REASONABLE_CHOICES,
    DEFAULT_BETA_RANGE,
    POPULATION_PERCENTILES,
)

__all__ = [
    # types
    "Point2D",
    "BoundingBox",
    "Interval",
    "AccessibilityNodeId",
    "TaskId",
    "StateId",
    "ActionId",
    "CostTuple",
    "TrajectoryStep",
    "Trajectory",
    "PolicyDistribution",
    # enums
    "AccessibilityRole",
    "BottleneckType",
    "CognitiveLaw",
    "EditOperationType",
    "RegressionVerdict",
    "PipelineStage",
    "ComparisonMode",
    "OutputFormat",
    "AlignmentPass",
    "Severity",
    "MotorChannel",
    "PerceptualChannel",
    # protocols
    "Parser",
    "Aligner",
    "CostModel",
    "PolicyComputer",
    "BottleneckClassifier",
    "RepairSynthesizer",
    "OutputFormatter",
    "PipelineStageExecutor",
    "Validator",
    "Serializable",
    "CacheProvider",
    "WCAGEvaluator",
    "GomsPredictor",
    "ChannelAnalyzer",
    # errors (all)
    "UsabilityOracleError",
    "ParseError",
    "InvalidAccessibilityTreeError",
    "MalformedHTMLError",
    "AlignmentError",
    "IncompatibleTreesError",
    "CostModelError",
    "InvalidParameterError",
    "ConvergenceError",
    "MDPError",
    "StateSpaceExplosionError",
    "UnreachableStateError",
    "PolicyError",
    "NumericalInstabilityError",
    "BisimulationError",
    "PartitionError",
    "BottleneckError",
    "ClassificationError",
    "ComparisonError",
    "InsufficientDataError",
    "RepairError",
    "SynthesisTimeoutError",
    "InfeasibleRepairError",
    "ConfigError",
    "ValidationError",
    "PipelineError",
    "StageError",
    "CacheError",
    # config
    "OracleConfig",
    "ParserConfig",
    "AlignmentConfig",
    "CognitiveConfig",
    "MDPConfig",
    "PolicyConfig",
    "BisimulationConfig",
    "ComparisonConfig",
    "RepairConfig",
    "PipelineConfig",
    "OutputConfig",
    # constants
    "FITTS_A_RANGE",
    "FITTS_B_RANGE",
    "HICK_A_RANGE",
    "HICK_B_RANGE",
    "WORKING_MEMORY_CAPACITY",
    "WORKING_MEMORY_DECAY_HALF_LIFE",
    "VISUAL_SEARCH_EFFICIENT_SLOPE",
    "VISUAL_SEARCH_INEFFICIENT_SLOPE",
    "MOTOR_PREPARATION_TIME",
    "MOTOR_EXECUTION_TIME",
    "PERCEPTION_TIME_VISUAL",
    "PERCEPTION_TIME_AUDITORY",
    "SACCADE_DURATION",
    "FIXATION_DURATION",
    "PIXEL_TO_MM",
    "DISPLAY_PPI",
    "CHANNEL_CAPACITIES",
    "MINIMUM_TARGET_SIZE_PX",
    "RECOMMENDED_TARGET_SIZE_PX",
    "MAX_REASONABLE_CHOICES",
    "DEFAULT_BETA_RANGE",
    "POPULATION_PERCENTILES",
]
