//! Solver backend emission: generate MPS and LP files from compiled MILP problems.
//!
//! Supports fixed-format MPS (80-column), free-format MPS, and CPLEX-style LP
//! file generation. Stubs for CIP (SCIP) and GRB (Gurobi) formats are provided.

use std::fmt::Write as FmtWrite;

use crate::pipeline::{IndicatorConstraint, MilpProblem, Sos1Set, VarType};
use crate::CompilerError;
use bicut_types::{ConstraintSense, OptDirection, VarBound};

/// Supported solver file formats.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OutputFormat {
    Mps,
    FreeMps,
    Lp,
    CipScip,
    GrbGurobi,
}

impl std::fmt::Display for OutputFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Mps => write!(f, "MPS"),
            Self::FreeMps => write!(f, "FreeMPS"),
            Self::Lp => write!(f, "LP"),
            Self::CipScip => write!(f, "CIP"),
            Self::GrbGurobi => write!(f, "GRB"),
        }
    }
}

/// Controls how a MILP is serialised to a solver file.
#[derive(Debug, Clone)]
pub struct EmissionConfig {
    pub format: OutputFormat,
    pub precision: usize,
    pub use_fixed_format_mps: bool,
    pub max_name_length: usize,
    pub include_comments: bool,
    pub compress_zeros: bool,
}

impl Default for EmissionConfig {
    fn default() -> Self {
        Self {
            format: OutputFormat::Mps,
            precision: 12,
            use_fixed_format_mps: true,
            max_name_length: 8,
            include_comments: true,
            compress_zeros: true,
        }
    }
}

/// The result of emitting a MILP to a solver file.
#[derive(Debug, Clone)]
pub struct EmissionResult {
    pub content: String,
    pub format: OutputFormat,
    pub num_vars_written: usize,
    pub num_constraints_written: usize,
    pub file_size_bytes: usize,
    pub warnings: Vec<String>,
}

// ── Helpers ────────────────────────────────────────────────────────

/// Extract all (row, coefficient) entries for column `col` from constraints.
pub fn get_column_entries(milp: &MilpProblem, col: usize) -> Vec<(usize, f64)> {
    milp.constraints
        .iter()
        .enumerate()
        .flat_map(|(row, con)| {
            con.coeffs
                .iter()
                .filter_map(move |&(c, v)| if c == col { Some((row, v)) } else { None })
        })
        .collect()
}

/// Default variable name when none is provided.
pub fn default_var_name(idx: usize) -> String {
    format!("x{}", idx)
}

/// Default constraint name when none is provided.
pub fn default_constraint_name(idx: usize) -> String {
    format!("c{}", idx)
}

fn resolve_var_name(milp: &MilpProblem, idx: usize) -> String {
    milp.variables
        .get(idx)
        .map(|v| &v.name)
        .filter(|s| !s.is_empty())
        .cloned()
        .unwrap_or_else(|| default_var_name(idx))
}

fn resolve_constraint_name(milp: &MilpProblem, idx: usize) -> String {
    milp.constraints
        .get(idx)
        .map(|c| &c.name)
        .filter(|s| !s.is_empty())
        .cloned()
        .unwrap_or_else(|| default_constraint_name(idx))
}

// ════════════════════════════════════════════════════════════════════
//  MPS Writer
// ════════════════════════════════════════════════════════════════════

/// Writes standard and free-format MPS files.
pub struct MpsWriter {
    config: EmissionConfig,
}

impl MpsWriter {
    pub fn new(config: EmissionConfig) -> Self {
        Self { config }
    }

    pub fn write(&self, milp: &MilpProblem) -> Result<EmissionResult, CompilerError> {
        if milp.variables.is_empty() {
            return Err(CompilerError::InvalidProblem(
                "Cannot emit MPS for a problem with zero variables".into(),
            ));
        }
        let mut warnings: Vec<String> = Vec::new();
        let nv = milp.variables.len();
        let nc = milp.constraints.len();
        let mut buf = String::with_capacity(nv * 80 + nc * 80);
        if self.config.include_comments {
            writeln!(buf, "* Generated by bicut-compiler emission module").unwrap();
            writeln!(buf, "* Variables: {}  Constraints: {}", nv, nc).unwrap();
        }
        buf.push_str(&self.write_name_section(milp));
        buf.push_str(&self.write_rows_section(milp));
        buf.push_str(&self.write_columns_section(milp));
        buf.push_str(&self.write_rhs_section(milp));
        let ranges = self.write_ranges_section(milp);
        if !ranges.is_empty() {
            buf.push_str(&ranges);
        }
        buf.push_str(&self.write_bounds_section(milp));
        let sos = self.write_sos_section(milp);
        if !sos.is_empty() {
            buf.push_str(&sos);
        }
        buf.push_str("ENDATA\n");
        for i in 0..nv {
            let raw = resolve_var_name(milp, i);
            if raw.len() > self.config.max_name_length && self.config.use_fixed_format_mps {
                warnings.push(format!(
                    "Variable name '{}' truncated to {} chars",
                    raw, self.config.max_name_length
                ));
            }
        }
        let size = buf.len();
        Ok(EmissionResult {
            content: buf,
            format: self.config.format,
            num_vars_written: nv,
            num_constraints_written: nc,
            file_size_bytes: size,
            warnings,
        })
    }

    pub fn write_name_section(&self, milp: &MilpProblem) -> String {
        let name = if milp.name.is_empty() {
            "UNNAMED"
        } else {
            &milp.name
        };
        format!("NAME          {}\n", name)
    }

    pub fn write_rows_section(&self, milp: &MilpProblem) -> String {
        let mut buf = String::from("ROWS\n");
        let sep = if self.config.use_fixed_format_mps {
            "  "
        } else {
            " "
        };
        writeln!(buf, " N{}OBJ", sep).unwrap();
        for (i, con) in milp.constraints.iter().enumerate() {
            let rt = match con.sense {
                ConstraintSense::Le => 'L',
                ConstraintSense::Ge => 'G',
                ConstraintSense::Eq => 'E',
            };
            writeln!(
                buf,
                " {}{}{}",
                rt,
                sep,
                self.sanitize_name(&resolve_constraint_name(milp, i))
            )
            .unwrap();
        }
        buf
    }

    pub fn write_columns_section(&self, milp: &MilpProblem) -> String {
        let mut buf = String::from("COLUMNS\n");
        let (mut in_int, mut mk) = (false, 0usize);
        for (col, var) in milp.variables.iter().enumerate() {
            let vname = self.sanitize_name(&resolve_var_name(milp, col));
            let is_int = matches!(var.var_type, VarType::Integer | VarType::Binary);
            if is_int && !in_int {
                mk += 1;
                self.marker(&mut buf, mk, "INTORG");
                in_int = true;
            }
            if !is_int && in_int {
                mk += 1;
                self.marker(&mut buf, mk, "INTEND");
                in_int = false;
            }
            let mut named: Vec<(String, f64)> = Vec::new();
            let obj = var.obj_coeff;
            if !self.skip(obj) {
                named.push(("OBJ".into(), obj));
            }
            for (row, val) in get_column_entries(milp, col) {
                if !self.skip(val) {
                    named.push((self.sanitize_name(&resolve_constraint_name(milp, row)), val));
                }
            }
            let mut idx = 0;
            while idx < named.len() {
                if self.config.use_fixed_format_mps && idx + 1 < named.len() {
                    writeln!(
                        buf,
                        "    {:8}  {:8}  {:>12}   {:8}  {:>12}",
                        vname,
                        named[idx].0,
                        self.format_value(named[idx].1),
                        named[idx + 1].0,
                        self.format_value(named[idx + 1].1)
                    )
                    .unwrap();
                    idx += 2;
                } else if self.config.use_fixed_format_mps {
                    writeln!(
                        buf,
                        "    {:8}  {:8}  {:>12}",
                        vname,
                        named[idx].0,
                        self.format_value(named[idx].1)
                    )
                    .unwrap();
                    idx += 1;
                } else {
                    writeln!(
                        buf,
                        "    {} {} {}",
                        vname,
                        named[idx].0,
                        self.format_value(named[idx].1)
                    )
                    .unwrap();
                    idx += 1;
                }
            }
        }
        if in_int {
            mk += 1;
            self.marker(&mut buf, mk, "INTEND");
        }
        buf
    }

    fn marker(&self, buf: &mut String, id: usize, kind: &str) {
        let mid = format!("M{:07}", id);
        if self.config.use_fixed_format_mps {
            writeln!(buf, "    {:8}  'MARKER'                 '{}'", mid, kind).unwrap();
        } else {
            writeln!(buf, "    {} 'MARKER' '{}'", mid, kind).unwrap();
        }
    }

    pub fn write_rhs_section(&self, milp: &MilpProblem) -> String {
        let mut buf = String::from("RHS\n");
        for (i, con) in milp.constraints.iter().enumerate() {
            let rhs = con.rhs;
            if self.config.compress_zeros && rhs.abs() < 1e-30 {
                continue;
            }
            let cn = self.sanitize_name(&resolve_constraint_name(milp, i));
            if self.config.use_fixed_format_mps {
                writeln!(
                    buf,
                    "    {:8}  {:8}  {:>12}",
                    "RHS1",
                    cn,
                    self.format_value(rhs)
                )
                .unwrap();
            } else {
                writeln!(buf, "    RHS1 {} {}", cn, self.format_value(rhs)).unwrap();
            }
        }
        buf
    }

    pub fn write_ranges_section(&self, milp: &MilpProblem) -> String {
        let mut buf = String::from("RANGES\n");
        let mut any = false;
        for (i, con) in milp.constraints.iter().enumerate() {
            let rv = con.range.unwrap_or(0.0);
            if rv.abs() < 1e-30 {
                continue;
            }
            any = true;
            let cn = self.sanitize_name(&resolve_constraint_name(milp, i));
            if self.config.use_fixed_format_mps {
                writeln!(
                    buf,
                    "    {:8}  {:8}  {:>12}",
                    "RNG1",
                    cn,
                    self.format_value(rv)
                )
                .unwrap();
            } else {
                writeln!(buf, "    RNG1 {} {}", cn, self.format_value(rv)).unwrap();
            }
        }
        if any {
            buf
        } else {
            String::new()
        }
    }

    pub fn write_bounds_section(&self, milp: &MilpProblem) -> String {
        let mut buf = String::from("BOUNDS\n");
        for (col, var) in milp.variables.iter().enumerate() {
            let vn = self.sanitize_name(&resolve_var_name(milp, col));
            let vt = var.var_type;
            let lb = var.lower_bound;
            let ub = var.upper_bound;
            if vt == VarType::Binary {
                self.bnd(&mut buf, "BV", &vn, None);
            } else if lb <= -1e20 && ub >= 1e20 {
                self.bnd(&mut buf, "FR", &vn, None);
            } else if (ub - lb).abs() < 1e-10 {
                self.bnd(&mut buf, "FX", &vn, Some(lb));
            } else {
                if lb <= -1e20 {
                    self.bnd(&mut buf, "MI", &vn, None);
                } else if (lb - 0.0).abs() > 1e-30 {
                    self.bnd(&mut buf, "LO", &vn, Some(lb));
                }
                if ub < 1e20 {
                    self.bnd(&mut buf, "UP", &vn, Some(ub));
                }
            }
        }
        buf
    }

    fn bnd(&self, buf: &mut String, kind: &str, var: &str, val: Option<f64>) {
        match (val, self.config.use_fixed_format_mps) {
            (Some(v), true) => writeln!(
                buf,
                " {:2} {:8}  {:8}  {:>12}",
                kind,
                "BND1",
                var,
                self.format_value(v)
            )
            .unwrap(),
            (Some(v), false) => {
                writeln!(buf, " {} BND1 {} {}", kind, var, self.format_value(v)).unwrap()
            }
            (None, true) => writeln!(buf, " {:2} {:8}  {:8}", kind, "BND1", var).unwrap(),
            (None, false) => writeln!(buf, " {} BND1 {}", kind, var).unwrap(),
        }
    }

    pub fn write_sos_section(&self, milp: &MilpProblem) -> String {
        if milp.sos1_sets.is_empty() {
            return String::new();
        }
        let mut buf = String::from("SOS\n");
        for sos in &milp.sos1_sets {
            let label = if sos.sos_type == 1 { "S1" } else { "S2" };
            let name = if sos.name.is_empty() {
                "SOS".to_string()
            } else {
                self.sanitize_name(&sos.name)
            };
            writeln!(buf, " {} {}", label, name).unwrap();
            for (j, &vi) in sos.members.iter().enumerate() {
                let w = sos.weights.get(j).copied().unwrap_or(j as f64 + 1.0);
                let vn = self.sanitize_name(&resolve_var_name(milp, vi));
                if self.config.use_fixed_format_mps {
                    writeln!(buf, "    {:8}  {:>12}", vn, self.format_value(w)).unwrap();
                } else {
                    writeln!(buf, "    {} {}", vn, self.format_value(w)).unwrap();
                }
            }
        }
        buf
    }

    /// Format a floating-point value with configured precision.
    pub fn format_value(&self, val: f64) -> String {
        if val == 0.0 {
            return "0".into();
        }
        let abs = val.abs();
        if abs >= 1e10 || (abs < 1e-4 && abs > 0.0) {
            format!("{:.*e}", self.config.precision, val)
        } else {
            let s = format!("{:.*}", self.config.precision, val);
            if s.contains('.') {
                let t = s.trim_end_matches('0').trim_end_matches('.');
                if t.is_empty() || t == "-" {
                    "0".into()
                } else {
                    t.into()
                }
            } else {
                s
            }
        }
    }

    /// Ensure a name is valid for MPS: replace invalid chars, truncate to max length.
    pub fn sanitize_name(&self, name: &str) -> String {
        let cleaned: String = name
            .chars()
            .map(|c| {
                if c.is_ascii_alphanumeric() || c == '_' || c == '.' {
                    c
                } else {
                    '_'
                }
            })
            .collect();
        if cleaned.is_empty() {
            return "_".into();
        }
        if cleaned.len() > self.config.max_name_length {
            cleaned[..self.config.max_name_length].to_string()
        } else {
            cleaned
        }
    }

    fn skip(&self, val: f64) -> bool {
        self.config.compress_zeros && val.abs() < 1e-30
    }
}

// ════════════════════════════════════════════════════════════════════
//  LP Writer
// ════════════════════════════════════════════════════════════════════

/// Writes CPLEX-style LP format files.
pub struct LpWriter {
    config: EmissionConfig,
}

impl LpWriter {
    pub fn new(config: EmissionConfig) -> Self {
        Self { config }
    }

    pub fn write(&self, milp: &MilpProblem) -> Result<EmissionResult, CompilerError> {
        if milp.variables.is_empty() {
            return Err(CompilerError::InvalidProblem(
                "Cannot emit LP for a problem with zero variables".into(),
            ));
        }
        let mut warnings: Vec<String> = Vec::new();
        let nv = milp.variables.len();
        let nc = milp.constraints.len();
        let mut buf = String::with_capacity(nv * 40 + nc * 60);
        if self.config.include_comments {
            writeln!(buf, "\\ Generated by bicut-compiler emission module").unwrap();
            writeln!(buf, "\\ Variables: {}  Constraints: {}", nv, nc).unwrap();
        }
        buf.push_str(&self.write_objective(milp));
        buf.push_str(&self.write_constraints(milp));
        buf.push_str(&self.write_bounds(milp));
        buf.push_str(&self.write_integers(milp));
        let sos = self.write_sos(milp);
        if !sos.is_empty() {
            buf.push_str(&sos);
        }
        buf.push_str("End\n");
        for i in 0..nv {
            let raw = resolve_var_name(milp, i);
            if raw.len() > 255 {
                warnings.push(format!(
                    "Variable name '{}...' exceeds 255 chars",
                    &raw[..40]
                ));
            }
        }
        let size = buf.len();
        Ok(EmissionResult {
            content: buf,
            format: OutputFormat::Lp,
            num_vars_written: nv,
            num_constraints_written: nc,
            file_size_bytes: size,
            warnings,
        })
    }

    pub fn write_objective(&self, milp: &MilpProblem) -> String {
        let kw = match milp.sense {
            OptDirection::Minimize => "Minimize",
            OptDirection::Maximize => "Maximize",
        };
        let mut buf = format!("{}\n  obj: ", kw);
        let mut first = true;
        for (col, var) in milp.variables.iter().enumerate() {
            let c = var.obj_coeff;
            if c.abs() < 1e-30 {
                continue;
            }
            buf.push_str(&Self::format_term(c, &resolve_var_name(milp, col), first));
            first = false;
        }
        if first {
            buf.push('0');
        }
        buf.push('\n');
        buf
    }

    pub fn write_constraints(&self, milp: &MilpProblem) -> String {
        if milp.constraints.is_empty() {
            return String::new();
        }
        let mut buf = String::from("Subject To\n");
        for (row, con) in milp.constraints.iter().enumerate() {
            let cname = resolve_constraint_name(milp, row);
            let lhs = self.format_constraint_lhs(row, milp);
            let sense = match con.sense {
                ConstraintSense::Le => "<=",
                ConstraintSense::Ge => ">=",
                ConstraintSense::Eq => "=",
            };
            let rhs = con.rhs;
            writeln!(buf, "  {}: {} {} {}", cname, lhs, sense, self.fmt_val(rhs)).unwrap();
        }
        buf
    }

    pub fn write_bounds(&self, milp: &MilpProblem) -> String {
        let mut buf = String::from("Bounds\n");
        for (col, var) in milp.variables.iter().enumerate() {
            let vn = resolve_var_name(milp, col);
            let vt = var.var_type;
            let lb = var.lower_bound;
            let ub = var.upper_bound;
            if vt == VarType::Binary {
                writeln!(buf, "  0 <= {} <= 1", vn).unwrap();
            } else if lb <= -1e20 && ub >= 1e20 {
                writeln!(buf, "  {} free", vn).unwrap();
            } else if ub >= 1e20 {
                writeln!(buf, "  {} <= {} <= +inf", self.fmt_val(lb), vn).unwrap();
            } else if lb <= -1e20 {
                writeln!(buf, "  -inf <= {} <= {}", vn, self.fmt_val(ub)).unwrap();
            } else {
                writeln!(
                    buf,
                    "  {} <= {} <= {}",
                    self.fmt_val(lb),
                    vn,
                    self.fmt_val(ub)
                )
                .unwrap();
            }
        }
        buf
    }

    pub fn write_integers(&self, milp: &MilpProblem) -> String {
        let mut gen: Vec<String> = Vec::new();
        let mut bin: Vec<String> = Vec::new();
        for (col, var) in milp.variables.iter().enumerate() {
            match var.var_type {
                VarType::Integer => gen.push(resolve_var_name(milp, col)),
                VarType::Binary => bin.push(resolve_var_name(milp, col)),
                _ => {}
            }
        }
        let mut buf = String::new();
        if !gen.is_empty() {
            buf.push_str("General\n");
            for chunk in gen.chunks(10) {
                writeln!(buf, "  {}", chunk.join(" ")).unwrap();
            }
        }
        if !bin.is_empty() {
            buf.push_str("Binary\n");
            for chunk in bin.chunks(10) {
                writeln!(buf, "  {}", chunk.join(" ")).unwrap();
            }
        }
        buf
    }

    pub fn write_sos(&self, milp: &MilpProblem) -> String {
        if milp.sos1_sets.is_empty() {
            return String::new();
        }
        let mut buf = String::from("SOS\n");
        for sos in &milp.sos1_sets {
            let label = if sos.sos_type == 1 { "S1" } else { "S2" };
            let name = if sos.name.is_empty() {
                "sos"
            } else {
                &sos.name
            };
            writeln!(buf, "  {} :: {}", name, label).unwrap();
            for (j, &vi) in sos.members.iter().enumerate() {
                let w = sos.weights.get(j).copied().unwrap_or(j as f64 + 1.0);
                writeln!(
                    buf,
                    "    {} : {}",
                    resolve_var_name(milp, vi),
                    self.fmt_val(w)
                )
                .unwrap();
            }
        }
        buf
    }

    /// Build the LHS expression string for a constraint row, e.g. `2 x1 + 3 x2 - x3`.
    pub fn format_constraint_lhs(&self, row: usize, milp: &MilpProblem) -> String {
        let entries = milp.constraints.get(row).map(|c| &c.coeffs);
        let mut first = true;
        let mut result = String::new();
        if let Some(entries) = entries {
            for &(col, coeff) in entries {
                if coeff.abs() < 1e-30 && self.config.compress_zeros {
                    continue;
                }
                result.push_str(&Self::format_term(
                    coeff,
                    &resolve_var_name(milp, col),
                    first,
                ));
                first = false;
            }
        }
        if result.is_empty() {
            "0".into()
        } else {
            result
        }
    }

    /// Format a single coefficient x variable term for LP output.
    pub fn format_term(coeff: f64, var_name: &str, is_first: bool) -> String {
        let abs = coeff.abs();
        let neg = coeff < 0.0;
        let cs = if (abs - 1.0).abs() < 1e-15 {
            String::new()
        } else {
            let r = format!("{}", abs);
            let t = if r.contains('.') {
                r.trim_end_matches('0').trim_end_matches('.').to_string()
            } else {
                r
            };
            format!("{} ", t)
        };
        if is_first {
            if neg {
                format!("- {}{}", cs, var_name)
            } else {
                format!("{}{}", cs, var_name)
            }
        } else if neg {
            format!(" - {}{}", cs, var_name)
        } else {
            format!(" + {}{}", cs, var_name)
        }
    }

    fn fmt_val(&self, val: f64) -> String {
        if val == 0.0 {
            return "0".into();
        }
        let s = format!("{:.*}", self.config.precision, val);
        if s.contains('.') {
            let t = s.trim_end_matches('0').trim_end_matches('.');
            if t.is_empty() || t == "-" {
                "0".into()
            } else {
                t.into()
            }
        } else {
            s
        }
    }
}

// ════════════════════════════════════════════════════════════════════
//  Top-level dispatch
// ════════════════════════════════════════════════════════════════════

/// Emit a MILP problem to the format specified in `config`.
pub fn emit(milp: &MilpProblem, config: &EmissionConfig) -> Result<EmissionResult, CompilerError> {
    match config.format {
        OutputFormat::Mps | OutputFormat::FreeMps => MpsWriter::new(config.clone()).write(milp),
        OutputFormat::Lp => LpWriter::new(config.clone()).write(milp),
        OutputFormat::CipScip => Err(CompilerError::InvalidProblem(
            "CIP (SCIP) format emission is not yet implemented".into(),
        )),
        OutputFormat::GrbGurobi => Err(CompilerError::InvalidProblem(
            "GRB (Gurobi) native format emission is not yet implemented".into(),
        )),
    }
}

// ════════════════════════════════════════════════════════════════════
//  Tests
// ════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    /// min 2x0 + 3x1 + x2
    /// s.t. x0 + x1       <= 10  (c0)
    ///      x0      + 2x2 >= 5   (c1)
    ///      x0 + x1 +  x2  = 8   (c2)
    /// x0 continuous [0,100], x1 binary, x2 integer [0,50]
    fn make_milp() -> MilpProblem {
        use crate::pipeline::{MilpConstraint, MilpVariable};

        let mut milp = MilpProblem::new("test_problem");
        milp.sense = OptDirection::Minimize;

        // Variables
        let mut x0 = MilpVariable::continuous("x0", 0.0, 100.0);
        x0.obj_coeff = 2.0;
        milp.add_variable(x0);

        let mut x1 = MilpVariable::binary("x1");
        x1.obj_coeff = 3.0;
        milp.add_variable(x1);

        let mut x2 = MilpVariable {
            name: "x2".into(),
            lower_bound: 0.0,
            upper_bound: 50.0,
            obj_coeff: 1.0,
            var_type: VarType::Integer,
        };
        milp.add_variable(x2);

        // Constraints
        let mut c0 = MilpConstraint::new("c0", ConstraintSense::Le, 10.0);
        c0.add_term(0, 1.0);
        c0.add_term(1, 1.0);
        milp.add_constraint(c0);

        let mut c1 = MilpConstraint::new("c1", ConstraintSense::Ge, 5.0);
        c1.add_term(0, 1.0);
        c1.add_term(2, 2.0);
        milp.add_constraint(c1);

        let mut c2 = MilpConstraint::new("c2", ConstraintSense::Eq, 8.0);
        c2.add_term(0, 1.0);
        c2.add_term(1, 1.0);
        c2.add_term(2, 1.0);
        milp.add_constraint(c2);

        milp
    }

    fn cfg(format: OutputFormat) -> EmissionConfig {
        EmissionConfig {
            format,
            precision: 6,
            use_fixed_format_mps: format == OutputFormat::Mps,
            max_name_length: 8,
            include_comments: false,
            compress_zeros: true,
        }
    }

    #[test]
    fn test_mps_name_section() {
        let w = MpsWriter::new(cfg(OutputFormat::Mps));
        let s = w.write_name_section(&make_milp());
        assert!(s.starts_with("NAME"));
        assert!(s.contains("test_problem"));
    }

    #[test]
    fn test_mps_rows_section_format() {
        let w = MpsWriter::new(cfg(OutputFormat::Mps));
        let s = w.write_rows_section(&make_milp());
        assert!(s.starts_with("ROWS\n"));
        assert!(s.contains(" N"));
        assert!(s.contains("OBJ"));
        assert!(s.contains(" L") && s.contains("c0"));
        assert!(s.contains(" G") && s.contains("c1"));
        assert!(s.contains(" E") && s.contains("c2"));
    }

    #[test]
    fn test_mps_columns_with_integers() {
        let w = MpsWriter::new(cfg(OutputFormat::Mps));
        let s = w.write_columns_section(&make_milp());
        assert!(s.starts_with("COLUMNS\n"));
        assert!(s.contains("INTORG"));
        assert!(s.contains("INTEND"));
        assert!(s.contains("x0") && s.contains("x1") && s.contains("x2"));
    }

    #[test]
    fn test_mps_bounds_bv_lo_up_fr() {
        use crate::pipeline::MilpVariable;

        let mut m = make_milp();
        m.add_variable(MilpVariable::continuous("x3", -1e21, 1e21));
        let w = MpsWriter::new(cfg(OutputFormat::Mps));
        let s = w.write_bounds_section(&m);
        assert!(s.starts_with("BOUNDS\n"));
        assert!(s.contains("BV") && s.contains("x1"));
        assert!(s.contains("UP"));
        assert!(s.contains("FR") && s.contains("x3"));
    }

    #[test]
    fn test_lp_objective_writing() {
        let w = LpWriter::new(cfg(OutputFormat::Lp));
        let s = w.write_objective(&make_milp());
        assert!(s.starts_with("Minimize\n"));
        assert!(s.contains("obj:"));
        assert!(s.contains("2 x0") && s.contains("3 x1") && s.contains("x2"));
    }

    #[test]
    fn test_lp_constraint_format() {
        let w = LpWriter::new(cfg(OutputFormat::Lp));
        let s = w.write_constraints(&make_milp());
        assert!(s.starts_with("Subject To\n"));
        assert!(s.contains("c0:") && s.contains("<=") && s.contains("10"));
        assert!(s.contains("c1:") && s.contains(">=") && s.contains("5"));
        assert!(s.contains("c2:") && s.contains("= 8"));
    }

    #[test]
    fn test_lp_bounds_section() {
        let w = LpWriter::new(cfg(OutputFormat::Lp));
        let s = w.write_bounds(&make_milp());
        assert!(s.starts_with("Bounds\n"));
        assert!(s.contains("0 <= x1 <= 1"));
        assert!(s.contains("x0") && s.contains("100"));
    }

    #[test]
    fn test_full_mps_roundtrip() {
        let r = emit(&make_milp(), &cfg(OutputFormat::Mps)).unwrap();
        assert_eq!(r.format, OutputFormat::Mps);
        assert_eq!(r.num_vars_written, 3);
        assert_eq!(r.num_constraints_written, 3);
        assert!(r.file_size_bytes > 0);
        let c = &r.content;
        let positions: Vec<usize> = ["NAME", "ROWS", "COLUMNS", "RHS\n", "BOUNDS", "ENDATA"]
            .iter()
            .map(|k| c.find(k).unwrap())
            .collect();
        for w in positions.windows(2) {
            assert!(w[0] < w[1]);
        }
    }

    #[test]
    fn test_full_lp_roundtrip() {
        let r = emit(&make_milp(), &cfg(OutputFormat::Lp)).unwrap();
        assert_eq!(r.format, OutputFormat::Lp);
        assert_eq!(r.num_vars_written, 3);
        let c = &r.content;
        let positions: Vec<usize> = ["Minimize", "Subject To", "Bounds", "End"]
            .iter()
            .map(|k| c.find(k).unwrap())
            .collect();
        for w in positions.windows(2) {
            assert!(w[0] < w[1]);
        }
        assert!(c.contains("Binary") && c.contains("General"));
    }

    #[test]
    fn test_value_formatting() {
        let w = MpsWriter::new(cfg(OutputFormat::Mps));
        assert_eq!(w.format_value(0.0), "0");
        assert_eq!(w.format_value(1.0), "1");
        assert_eq!(w.format_value(-3.5), "-3.5");
        assert_eq!(w.format_value(100.0), "100");
        assert!(w.format_value(1e-8).contains('e'));
        assert!(w.format_value(1e15).contains('e'));
    }

    #[test]
    fn test_sanitize_name() {
        let c = EmissionConfig {
            max_name_length: 8,
            ..cfg(OutputFormat::Mps)
        };
        let w = MpsWriter::new(c);
        assert_eq!(w.sanitize_name("x0"), "x0");
        assert_eq!(w.sanitize_name("very_long_variable_name"), "very_lon");
        assert_eq!(w.sanitize_name("has space"), "has_spac");
        assert_eq!(w.sanitize_name("a+b-c"), "a_b_c");
        assert_eq!(w.sanitize_name(""), "_");
    }

    #[test]
    fn test_format_term() {
        assert_eq!(LpWriter::format_term(2.0, "x1", true), "2 x1");
        assert_eq!(LpWriter::format_term(-3.0, "x2", true), "- 3 x2");
        assert_eq!(LpWriter::format_term(1.0, "x3", true), "x3");
        assert_eq!(LpWriter::format_term(-1.0, "x4", true), "- x4");
        assert_eq!(LpWriter::format_term(5.0, "y", false), " + 5 y");
        assert_eq!(LpWriter::format_term(-7.0, "z", false), " - 7 z");
        assert_eq!(LpWriter::format_term(1.0, "w", false), " + w");
    }

    #[test]
    fn test_get_column_entries() {
        let m = make_milp();
        assert_eq!(
            get_column_entries(&m, 0),
            vec![(0, 1.0), (1, 1.0), (2, 1.0)]
        );
        assert_eq!(get_column_entries(&m, 2), vec![(1, 2.0), (2, 1.0)]);
    }

    #[test]
    fn test_empty_problem_errors() {
        let empty = MilpProblem::new("");
        assert!(emit(&empty, &cfg(OutputFormat::Mps)).is_err());
        assert!(emit(&empty, &cfg(OutputFormat::Lp)).is_err());
    }

    #[test]
    fn test_sos_section_mps() {
        let mut m = make_milp();
        m.sos1_sets.push(Sos1Set {
            name: "sos_set1".into(),
            sos_type: 1,
            members: vec![0, 1],
            weights: vec![1.0, 2.0],
        });
        let w = MpsWriter::new(cfg(OutputFormat::Mps));
        let s = w.write_sos_section(&m);
        assert!(s.starts_with("SOS\n"));
        assert!(s.contains("S1") && s.contains("sos_set1"));
        assert!(s.contains("x0") && s.contains("x1"));
    }

    #[test]
    fn test_maximize_lp() {
        let mut m = make_milp();
        m.sense = OptDirection::Maximize;
        let w = LpWriter::new(cfg(OutputFormat::Lp));
        assert!(w.write_objective(&m).starts_with("Maximize\n"));
    }

    #[test]
    fn test_free_mps_format() {
        let c = EmissionConfig {
            format: OutputFormat::FreeMps,
            use_fixed_format_mps: false,
            ..cfg(OutputFormat::FreeMps)
        };
        let r = emit(&make_milp(), &c).unwrap();
        assert_eq!(r.format, OutputFormat::FreeMps);
        assert!(r.content.contains("NAME") && r.content.contains("ENDATA"));
    }

    #[test]
    fn test_default_names_fallback() {
        let mut m = make_milp();
        // Clear variable and constraint names to test fallback naming
        for var in &mut m.variables {
            var.name = String::new();
        }
        for con in &mut m.constraints {
            con.name = String::new();
        }
        let mw = MpsWriter::new(cfg(OutputFormat::Mps));
        let rows = mw.write_rows_section(&m);
        assert!(rows.contains("c0") && rows.contains("c1"));
        let lw = LpWriter::new(cfg(OutputFormat::Lp));
        let obj = lw.write_objective(&m);
        assert!(obj.contains("x0") && obj.contains("x1"));
    }

    #[test]
    fn test_cip_grb_not_implemented() {
        let m = make_milp();
        let c1 = EmissionConfig {
            format: OutputFormat::CipScip,
            ..cfg(OutputFormat::Mps)
        };
        assert!(emit(&m, &c1).is_err());
        let c2 = EmissionConfig {
            format: OutputFormat::GrbGurobi,
            ..cfg(OutputFormat::Mps)
        };
        assert!(emit(&m, &c2).is_err());
    }
}

// ── Type aliases for crate-level re-exports ────────────────────────

/// The emitted model output (alias for [`EmissionResult`]).
pub type EmittedModel = EmissionResult;

/// The top-level emitter (alias for [`MpsWriter`]).
pub type Emitter = MpsWriter;
