pub mod vector;
pub mod matrix;
pub mod quaternion;
pub mod units;
pub mod quantity;
pub mod particle;
pub mod field;
pub mod state;
pub mod trajectory;
pub mod conservation_law;
pub mod violation;
pub mod system;
pub mod tolerance;
pub mod time_series;
pub mod interpolation;
pub mod interval;
pub mod mesh;
pub mod boundary;
pub mod phase_space;
pub mod nalgebra_interop;
pub mod ndarray_interop;

pub use vector::{Vec2, Vec3, Vec4};
pub use matrix::{Mat3, Mat4};
pub use quaternion::Quaternion;
pub use units::{UnitSystem, Dimension, Unit};
pub use quantity::Quantity;
pub use particle::{Particle, ParticleSystem};
pub use field::{ScalarField, VectorField};
pub use state::SimulationState;
pub use trajectory::Trajectory;
pub use conservation_law::{ConservationLaw, ConservationKind, ConservedQuantity};
pub use violation::{Violation, ViolationSeverity, ViolationReport};
pub use system::{PhysicalSystem, SystemConfig};
pub use tolerance::{Tolerance, ToleranceKind};
pub use time_series::TimeSeries;
pub use interpolation::{LinearInterpolator, CubicInterpolator, HermiteInterpolator};
pub use interval::Interval;
pub use mesh::{Mesh1D, Mesh2D, Mesh3D};
pub use boundary::{BoundaryCondition, BoundaryKind};
pub use phase_space::{PhaseSpacePoint, SymplecticForm};
