"""MARACE reporting module.

Provides race reports, replay reports, proof certificates,
and visualization tools for multi-agent race verification results.
"""

from .race_report import (
    RaceReport,
    ReportSection,
    SummaryGenerator,
    DetailedRaceReport,
    ComparisonReport,
    ReportFormatter,
    TextReportFormatter,
    JSONReportFormatter,
    HTMLReportFormatter,
    LaTeXReportFormatter,
)
from .replay_report import (
    ReplayReport,
    TimelineRenderer,
    StateTrajectoryPlotter,
    CriticalMomentHighlighter,
    CounterfactualComparison,
)
from .certificates import (
    ProofCertificate,
    CertificateGenerator,
    CertificateVerifier,
    CertificateFormat,
    CoverageMap,
    CertificateChain,
)
from .proof_certificates import (
    CertificateBuilder,
    IndependentChecker,
    CertificateSerializer,
    CertificateChainVerifier,
    CertificateFormatV2,
    IndependentCertificateChecker,
    FarkasCertificate,
    InductiveWitnessStep,
    HBDerivationStep,
)
from .tcb_analysis import (
    TCBComponent,
    TCBReport,
    TCBAnalyzer,
    TrustLevel,
    SoundnessArgument,
    AletheCertificateAdapter,
    IndependentChecker as StandaloneChecker,
    StandaloneCheckResult,
)
from .visualization import (
    StateSpaceVisualizer,
    ScheduleSpaceVisualizer,
    RaceRegionVisualizer,
    InteractionGroupVisualizer,
    ConvergenceVisualizer,
    MetricsDashboard,
    ASCIIVisualizer,
)

__all__ = [
    "RaceReport",
    "ReportSection",
    "SummaryGenerator",
    "DetailedRaceReport",
    "ComparisonReport",
    "ReportFormatter",
    "TextReportFormatter",
    "JSONReportFormatter",
    "HTMLReportFormatter",
    "LaTeXReportFormatter",
    "ReplayReport",
    "TimelineRenderer",
    "StateTrajectoryPlotter",
    "CriticalMomentHighlighter",
    "CounterfactualComparison",
    "ProofCertificate",
    "CertificateGenerator",
    "CertificateVerifier",
    "CertificateFormat",
    "CoverageMap",
    "CertificateChain",
    "CertificateBuilder",
    "IndependentChecker",
    "CertificateSerializer",
    "CertificateChainVerifier",
    "CertificateFormatV2",
    "IndependentCertificateChecker",
    "FarkasCertificate",
    "InductiveWitnessStep",
    "HBDerivationStep",
    "StateSpaceVisualizer",
    "ScheduleSpaceVisualizer",
    "RaceRegionVisualizer",
    "InteractionGroupVisualizer",
    "ConvergenceVisualizer",
    "MetricsDashboard",
    "ASCIIVisualizer",
    "TCBComponent",
    "TCBReport",
    "TCBAnalyzer",
    "TrustLevel",
    "SoundnessArgument",
    "AletheCertificateAdapter",
    "StandaloneChecker",
    "StandaloneCheckResult",
]
