"""
Independent certificate verification for TN-Check.

Provides a standalone verifier that audits error certificates
without re-running the computation. This addresses the critique
that certificates are generated by the same system that produces
results, providing no independent check.

Usage:
    from tn_check.verifier import CertificateVerifier, VerificationTrace

    # Load a trace from a previous computation
    trace = VerificationTrace.from_json("trace.json")

    # Verify independently
    verifier = CertificateVerifier()
    report = verifier.verify(trace)
    print(report.summary())
"""

from tn_check.verifier.trace import (
    VerificationTrace,
    StepRecord,
    FSPBoundRecord,
    CSLCheckRecord,
    ClampingProofRecord,
)
from tn_check.verifier.checker import (
    CertificateVerifier,
    VerificationReport,
    CheckResult,
)

__all__ = [
    "VerificationTrace",
    "StepRecord",
    "FSPBoundRecord",
    "CSLCheckRecord",
    "ClampingProofRecord",
    "CertificateVerifier",
    "VerificationReport",
    "CheckResult",
]
