"""Sequential importance sampling engine for MARACE.

Provides statistically rigorous probability bounds on interaction race
occurrence by importance-sampling over the schedule distribution
conditioned on abstract-interpretation-identified race regions,
with cross-entropy adaptation for proposal construction.
"""

from marace.sampling.schedule_space import (
    Schedule,
    ScheduleConstraint,
    ScheduleSpace,
    ScheduleGenerator,
    ScheduleNeighborhood,
    ContinuousSchedule,
    ScheduleDistance,
)
from marace.sampling.importance_sampling import (
    ImportanceWeights,
    EffectiveSampleSize,
    ConfidenceInterval,
    ProposalDistribution,
    UniformProposal,
    AbstractGuidedProposal,
    ImportanceSampler,
    SequentialImportanceSampler,
    RaceProbabilityEstimator,
    SelfNormalizedISEstimator,
    ESSAdaptiveResampler,
    ParetoSmoothedIS,
    ControlVariateValidator,
)
from marace.sampling.cross_entropy import (
    ParametricProposal,
    CEIteration,
    EliteSampleSelector,
    ProposalConvergence,
    AdaptiveTemperature,
    MultiModalProposal,
    CrossEntropyOptimizer,
    CEConvergenceProof,
    KLDivergenceMonitor,
    CEConvergenceDiagnostics,
)
from marace.sampling.statistics import (
    SampleStatistics,
    ConfidenceBound,
    StratifiedEstimator,
    ControlVariate,
    BayesianEstimator,
    ConvergenceDiagnostics,
)
from marace.sampling.distribution import (
    ScheduleMeasure,
    UniformHBConsistentMeasure,
    LatencyWeightedMeasure,
    PlackettLuceMeasure,
    MixtureScheduleMeasure,
    DistributionValidator,
    MixedLogitPlackettLuce,
    ESSMonitor,
    WeightDegeneracyDiagnostics,
)
from marace.sampling.concentration import (
    SelfNormalizedBound,
    EmpiricalBernsteinBound,
    AndersonDarlingTest,
    AdaptiveBoundSelector,
    FiniteSampleGuarantee,
    CoverageValidator,
    ConvergenceTheory,
    HoeffdingSelfNormalizedBound,
    MartingaleStoppingCriterion,
)

__all__ = [
    "Schedule",
    "ScheduleConstraint",
    "ScheduleSpace",
    "ScheduleGenerator",
    "ScheduleNeighborhood",
    "ContinuousSchedule",
    "ScheduleDistance",
    "ImportanceWeights",
    "EffectiveSampleSize",
    "ConfidenceInterval",
    "ProposalDistribution",
    "UniformProposal",
    "AbstractGuidedProposal",
    "ImportanceSampler",
    "SequentialImportanceSampler",
    "RaceProbabilityEstimator",
    "SelfNormalizedISEstimator",
    "ESSAdaptiveResampler",
    "ParetoSmoothedIS",
    "ControlVariateValidator",
    "ParametricProposal",
    "CEIteration",
    "EliteSampleSelector",
    "ProposalConvergence",
    "AdaptiveTemperature",
    "MultiModalProposal",
    "CrossEntropyOptimizer",
    "CEConvergenceProof",
    "KLDivergenceMonitor",
    "CEConvergenceDiagnostics",
    "SampleStatistics",
    "ConfidenceBound",
    "StratifiedEstimator",
    "ControlVariate",
    "BayesianEstimator",
    "ConvergenceDiagnostics",
    "ScheduleMeasure",
    "UniformHBConsistentMeasure",
    "LatencyWeightedMeasure",
    "PlackettLuceMeasure",
    "MixtureScheduleMeasure",
    "DistributionValidator",
    "MixedLogitPlackettLuce",
    "ESSMonitor",
    "WeightDegeneracyDiagnostics",
    "SelfNormalizedBound",
    "EmpiricalBernsteinBound",
    "AndersonDarlingTest",
    "AdaptiveBoundSelector",
    "FiniteSampleGuarantee",
    "CoverageValidator",
    "ConvergenceTheory",
    "HoeffdingSelfNormalizedBound",
    "MartingaleStoppingCriterion",
]
