"""
usability_oracle.utils — Shared utilities for the usability oracle.

Provides mathematical functions, graph algorithms, information-theoretic
computations, sampling methods, timing helpers, logging setup, and
serialisation utilities.
"""

from __future__ import annotations

from usability_oracle.utils.math import (
    entropy,
    jensen_shannon_divergence,
    kl_divergence,
    log2_safe,
    log_sum_exp,
    mutual_information,
    normalize_distribution,
    softmax,
    total_variation_distance,
    wasserstein_distance,
)
from usability_oracle.utils.timing import Timer, TimingReport, format_timing, timed
from usability_oracle.utils.logging import LogContext, get_logger, setup_logging
from usability_oracle.utils.serialization import (
    DataclassEncoder,
    NumpyEncoder,
    deserialize_from_json,
    load_from_file,
    save_to_file,
    serialize_to_json,
)
from usability_oracle.utils.caching import (
    CacheStats,
    ContentAddressableStore,
    CostCache,
    LRUCache,
    MemoizedFunction,
    PolicyCache,
    TreeCache,
    cache_stats,
    clear_all_caches,
)
from usability_oracle.utils.profiling import (
    MemoryTracker,
    PipelineProfiler,
    ProfileReport,
    StageTimer,
    compare_profiles,
    format_profile,
    hotspot_analysis,
    memory_report,
    memory_tracked,
    timed as profiling_timed,
)
from usability_oracle.utils.vectorized import (
    BenchmarkResult,
    batch_interval_arithmetic,
    batch_softmax,
    benchmark,
    parallel_cost_computation,
    sparse_transition_multiply,
    vectorized_fitts,
    vectorized_hick,
    vectorized_kl_divergence,
    vectorized_visual_search,
)
from usability_oracle.utils.vectorized_ops import (
    SIMDLayout,
    batch_free_energy,
    batch_information_gain,
    batch_js_divergence,
    batch_kl_divergence,
    batch_log_policy,
    batch_mutual_information,
    batch_softmax_stable,
    bellman_backup_dense,
    bellman_backup_sparse,
    bisimulation_distance,
    sparse_bellman_operator,
    sparse_kronecker_product,
    sparse_policy_evaluation,
    value_iteration_step,
    vectorized_fitts_batch,
    vectorized_fitts_multi,
    vectorized_hick_batch,
)
from usability_oracle.utils.lru_cache import (
    CacheStatistics,
    CacheWarmer,
    ContentAddressableCache,
    HierarchicalCache,
    InvalidationPolicy,
    InvalidationRule,
    TypedLRUCache,
    deserialize_cache,
    serialize_cache,
)
from usability_oracle.utils.profiling_ext import (
    BenchmarkSuite,
    CallCounter,
    MemoryContext,
    RegressionDetector,
    StackSample,
    TimingContext,
    TimingResult,
    collect_stack_samples,
    generate_flamegraph_data,
    statistical_timing,
)
from usability_oracle.utils.sparse import (
    CompressedBeliefState,
    SparseCostVector,
    SparseMDP,
    SparsePolicy,
    factored_transition,
    sparse_csr_matmat,
    sparse_csr_matvec,
    sparse_kronecker,
    sparse_policy_transition,
    sparse_value_iteration,
)
from usability_oracle.utils.parallel import (
    BatchResult,
    ProcessPool,
    ProgressTracker,
    ThreadPool,
    async_batch_process,
    chunked_parallel_map,
    resource_aware_workers,
    retry_map,
)
from usability_oracle.utils.numerical import (
    WelfordAccumulator,
    assert_close,
    check_conditioning,
    condition_number,
    gauss_legendre_quadrature,
    gradient_check,
    jacobian_numerical,
    kahan_cumsum,
    kahan_sum,
    log_softmax,
    logsumexp_stable,
    relative_error,
    simpsons,
    softmax_stable,
    trapezoid,
)

__all__ = [
    # math
    "entropy",
    "jensen_shannon_divergence",
    "kl_divergence",
    "log2_safe",
    "log_sum_exp",
    "mutual_information",
    "normalize_distribution",
    "softmax",
    "total_variation_distance",
    "wasserstein_distance",
    # timing
    "Timer",
    "TimingReport",
    "format_timing",
    "timed",
    # logging
    "LogContext",
    "get_logger",
    "setup_logging",
    # serialization
    "DataclassEncoder",
    "NumpyEncoder",
    "deserialize_from_json",
    "load_from_file",
    "save_to_file",
    "serialize_to_json",
    # caching
    "CacheStats",
    "ContentAddressableStore",
    "CostCache",
    "LRUCache",
    "MemoizedFunction",
    "PolicyCache",
    "TreeCache",
    "cache_stats",
    "clear_all_caches",
    # profiling
    "MemoryTracker",
    "PipelineProfiler",
    "ProfileReport",
    "StageTimer",
    "compare_profiles",
    "format_profile",
    "hotspot_analysis",
    "memory_report",
    "memory_tracked",
    "profiling_timed",
    # vectorized
    "BenchmarkResult",
    "batch_interval_arithmetic",
    "batch_softmax",
    "benchmark",
    "parallel_cost_computation",
    "sparse_transition_multiply",
    "vectorized_fitts",
    "vectorized_hick",
    "vectorized_kl_divergence",
    "vectorized_visual_search",
    # vectorized_ops
    "SIMDLayout",
    "batch_free_energy",
    "batch_information_gain",
    "batch_js_divergence",
    "batch_kl_divergence",
    "batch_log_policy",
    "batch_mutual_information",
    "batch_softmax_stable",
    "bellman_backup_dense",
    "bellman_backup_sparse",
    "bisimulation_distance",
    "sparse_bellman_operator",
    "sparse_kronecker_product",
    "sparse_policy_evaluation",
    "value_iteration_step",
    "vectorized_fitts_batch",
    "vectorized_fitts_multi",
    "vectorized_hick_batch",
    # lru_cache
    "CacheStatistics",
    "CacheWarmer",
    "ContentAddressableCache",
    "HierarchicalCache",
    "InvalidationPolicy",
    "InvalidationRule",
    "TypedLRUCache",
    "deserialize_cache",
    "serialize_cache",
    # profiling_ext
    "BenchmarkSuite",
    "CallCounter",
    "MemoryContext",
    "RegressionDetector",
    "StackSample",
    "TimingContext",
    "TimingResult",
    "collect_stack_samples",
    "generate_flamegraph_data",
    "statistical_timing",
    # sparse
    "CompressedBeliefState",
    "SparseCostVector",
    "SparseMDP",
    "SparsePolicy",
    "factored_transition",
    "sparse_csr_matmat",
    "sparse_csr_matvec",
    "sparse_kronecker",
    "sparse_policy_transition",
    "sparse_value_iteration",
    # parallel
    "BatchResult",
    "ProcessPool",
    "ProgressTracker",
    "ThreadPool",
    "async_batch_process",
    "chunked_parallel_map",
    "resource_aware_workers",
    "retry_map",
    # numerical
    "WelfordAccumulator",
    "assert_close",
    "check_conditioning",
    "condition_number",
    "gauss_legendre_quadrature",
    "gradient_check",
    "jacobian_numerical",
    "kahan_cumsum",
    "kahan_sum",
    "log_softmax",
    "logsumexp_stable",
    "relative_error",
    "simpsons",
    "softmax_stable",
    "trapezoid",
]
