"""
Property checking module for CoaCert-TLA.

Provides CTL* model checking, safety verification, liveness checking
under fairness, differential testing (original vs quotient), and
temporal logic formula handling.
"""

from .temporal_logic import (
    TemporalFormula,
    Atomic,
    TrueFormula,
    FalseFormula,
    Not,
    And,
    Or,
    Implies,
    Iff,
    ExistsPath,
    ForallPath,
    Next,
    Until,
    Release,
    Finally,
    Globally,
    WeakUntil,
    FormulaVisitor,
    FormulaParseError,
    to_nnf,
    simplify,
    is_stuttering_invariant,
    is_ctl_star_without_next,
    is_ctl,
    is_ltl,
    atomic_propositions,
    parse_formula,
    EX,
    EF,
    EG,
    EU,
    AX,
    AF,
    AG,
    AU,
)

from .ctl_star import (
    KripkeAdapter,
    CTLCheckResult,
    CTLLabeler,
    CounterexampleGenerator,
    CTLStarChecker,
    check_invariant,
    check_reachability,
    check_response,
)

from .safety import (
    SafetyKind,
    SafetyProperty,
    ActionSafetyProperty,
    SafetyCheckResult,
    InductiveCheckResult,
    StrengtheningCandidate,
    SafetyChecker,
    make_ap_invariant,
    make_exclusion_invariant,
    make_type_invariant,
    make_action_constraint,
)

from .liveness import (
    FairnessKind,
    FairnessSpec,
    LivenessKind,
    LivenessProperty,
    LivenessCheckResult,
    LivenessChecker,
    make_infinitely_often,
    make_eventually_always,
    make_leads_to,
    make_weak_fairness,
    make_strong_fairness,
)

from .differential import (
    DiscrepancyKind,
    Discrepancy,
    DifferentialStats,
    RandomPropertyGenerator,
    BenchmarkPropertySuite,
    DifferentialTester,
)

__all__ = [
    # temporal_logic
    "TemporalFormula",
    "Atomic",
    "TrueFormula",
    "FalseFormula",
    "Not",
    "And",
    "Or",
    "Implies",
    "Iff",
    "ExistsPath",
    "ForallPath",
    "Next",
    "Until",
    "Release",
    "Finally",
    "Globally",
    "WeakUntil",
    "FormulaVisitor",
    "FormulaParseError",
    "to_nnf",
    "simplify",
    "is_stuttering_invariant",
    "is_ctl_star_without_next",
    "is_ctl",
    "is_ltl",
    "atomic_propositions",
    "parse_formula",
    "EX",
    "EF",
    "EG",
    "EU",
    "AX",
    "AF",
    "AG",
    "AU",
    # ctl_star
    "KripkeAdapter",
    "CTLCheckResult",
    "CTLLabeler",
    "CounterexampleGenerator",
    "CTLStarChecker",
    "check_invariant",
    "check_reachability",
    "check_response",
    # safety
    "SafetyKind",
    "SafetyProperty",
    "ActionSafetyProperty",
    "SafetyCheckResult",
    "InductiveCheckResult",
    "StrengtheningCandidate",
    "SafetyChecker",
    "make_ap_invariant",
    "make_exclusion_invariant",
    "make_type_invariant",
    "make_action_constraint",
    # liveness
    "FairnessKind",
    "FairnessSpec",
    "LivenessKind",
    "LivenessProperty",
    "LivenessCheckResult",
    "LivenessChecker",
    "make_infinitely_often",
    "make_eventually_always",
    "make_leads_to",
    "make_weak_fairness",
    "make_strong_fairness",
    # differential
    "DiscrepancyKind",
    "Discrepancy",
    "DifferentialStats",
    "RandomPropertyGenerator",
    "BenchmarkPropertySuite",
    "DifferentialTester",
]
